name: Deploy Project
on:
  push:
    branches:
      # This workflow is triggered when a push to dev/<xyz_branch_name> is made
      - "dev/**"
jobs:
  run_test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      # Each step is an action that will get executed during this job run
      # Checkout code from github repository
      - name: Checkout code
        uses: actions/checkout@v4
      # Install NodeJS v21
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 21
      # Install npm dependencies
      - name: Install dependencies
        run: npm ci
      # Run tests
      - name: Run tests
        run: npm run test
      # Upload coverage reports as artifacts
      - name: Publish coverage reports
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: ./coverage
  
  unpack:
    name: Unpack artifacts
    runs-on: ubuntu-latest
    needs: run_test
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: coverage-report
      - name: Display coverage report contents
        run: ls -R 

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    # To avoid jobs from running in parallel, use needs: <dependent_job_name>
    needs: run_test
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 21
      - name: Install dependencies
        run: npm ci
      - name: Deploy
        run: echo "Deploying!"
