name: Reusable Deployment
on: workflow_call
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest\
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 21
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: ${{ steps.cache.outputs.cache_hit != 'true' }}
        run: npm ci
      - name: Deploy
        run: echo "Deploying!"
