name: Reusable Deployment
on: 
    workflow_call:
        inputs:
            artifact-name:
                description: The name of the report artifact files
                required: false
                default: coverage-report
                type: string
jobs:
  unpack:
    name: Unpack artifacts
    runs-on: ubuntu-latest
    if: failure()
    steps:
      # - name: Display output variable from test job
      #   run: echo "${{ needs.run_test.outputs.can_unpack }}"
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: Display coverage report contents
        run: ls -R

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 21
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: ${{ steps.cache.outputs.cache_hit != 'true' }}
        run: npm ci
      - name: Deploy
        run: echo "Deploying!"
